### ISSUE TITLE
Official Document / Polymer / Tools / Polymer CLI Commands

### ISSUE THREAD

**Issue by takanorip** [Polymer-Japan/docs#18]
_From @ecouffes on November 3, 2017 8:21_

_Copied from original issue: Polymer-Japan/translation#98_

**Comment by ecouffes** [comment]
## 本家ページ
https://www.polymer-project.org/2.0/docs/tools/polymer-cli-commands

## 翻訳ページ
https://docs.polymer-jp.org/2.0/docs/tools/polymer-cli-commands
