### ISSUE TITLE
GitLocalize による日本語化

### ISSUE THREAD

**Issue by aggre** [Polymer-Japan/docs#3]
作成したプロジェクト: https://gitlocalize.com/repo/469

## 課題

`/app/2.0` などのディレクトリ名は GitLocalize においてファイルとして扱われてしまうのか、翻訳対象にできない問題。

GitLocalize からの回答

> Thanks for reaching out and apologize for the inconvenience. We have identified the issue and are now fixing it. Let me get this back to you soon when it's solved.

ディレクトリ名にピリオドが含まれる場合は *現時点では* 使えない様子。

## 対策

GitLocalize が利用可能になった状況を想定したディレクトリ構成で日本語化を進める。

`/app/_locales/ja` ディレクトリに翻訳済みの Markdown を追加すると、未翻訳の Markdown よりも優先して表示されるように変更済み( https://github.com/Polymer-Japan/docs/commit/ace746100b0dd476f41e70b6755d7449ed3fc3ea, https://github.com/Polymer-Japan/docs/commit/143f6745d9ba12b0b0473e922721e5f865273da0 )。

翻訳対象の Markdown は `/app` ディレクトリ。

**Comment by aggre** [comment]
GitLocalize よりディレクトリ名の問題が解決されたとの連絡がありました。

**Comment by aggre** [comment]
フォークしてテスト中 https://github.com/aggre/docs

**Comment by sizuhiko** [comment]
対応早い！

**Comment by aggre** [comment]
まだファイルの Sync ができていないので使えません😷 https://gitlocalize.com/repo/473

**Comment by aggre** [comment]
テスト用のリポジトリで試していたところ、 `app` 以下を Sync 対象にしているときに `app/_locales/%lang%` などに翻訳ファイルを置けないようです。 `locales/%lang%` などを翻訳ファイルの置き場に変えたら Sync できました。そっかそっかーだよねーという感じです。

Gulp 書き換える必要があるので後ほど対応します。

**Comment by aggre** [comment]
GitLocalize のアップデートにより対応が不要になりました。
